services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # 🔥 IMPORTANTE (EVITA TIMEOUTS)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      echo "Esperando Kafka..."
      cub kafka-ready -b kafka:9092 1 30

      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic queries --partitions 3 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic queries.retry --partitions 3 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic queries.dlq --partitions 3 --replication-factor 1

      echo "Topicos creados correctamente"
      kafka-topics --bootstrap-server kafka:9092 --list

  cache-service:
    build: .
    ports:
      - "8000:8000"
    environment:
       RESPONSE_URL: http://response-generator:8001/query

  response-generator:
    build: ../Consultas
    ports:
      - "8001:8001"
    volumes:
      - ../Consultas/data:/data

  traffic-generator:
    build: ../Generador_Trafico
    depends_on:
      - kafka-init
      - cache-service
      - response-generator
    environment:
      - VERSION=v2
      - MODE=uniform
    volumes:
      - ../Generador_Trafico/images:/app/images

  consumer:
    build: ../consumer
    depends_on:
      - kafka-init
      - cache-service
      - response-generator
    environment:
      - MAX_RETRIES=5
      - RETRY_DELAY_SECONDS=8
  
  dlq-worker:
    build: ../consumer
    command: python /app/dlq_queries.py
    container_name: dlq-worker
    depends_on:
      kafka-init:
        condition: service_completed_successfully

  retry-worker:
    build: ../consumer
    command: python retry_worker.py
    container_name: retry-worker
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      cache-service:
        condition: service_started
    environment:
      - KAFKA_BROKER=kafka:9092
      - CACHE_URL=http://cache-service:8000/query
      - MAX_RETRIES=3
      - RETRY_DELAY_SECONDS=2